default_context:
  project_name: 'edgevalue'
  project_slug: 'edgevalue'
  domain_main: 'edgevalue.com'
  domain_staging: 'stag.edgevalue.com'
  docker_swarm_stack_name_main: 'edgevalue-com'
  docker_swarm_stack_name_staging: 'stag-edgevalue-com'
  secret_key: 'a6444f9175a3a844d330474cd510189ce7b05106435a1f1b410579b117bd1896'
  first_superuser: 'admin@edgevalue.com'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.edgevalue.com", "https://stag.edgevalue.com", "https://edgevalue.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@edgevalue.com'
  postgres_password: 'admin'
  pgadmin_default_user: 'admin@edgevalue.com'
  pgadmin_default_user_password: 'admin'
  traefik_constraint_tag: 'edgevalue.com'
  traefik_constraint_tag_staging: 'stag.edgevalue.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
