"""Changed some columns from Financial Statement table and added isin column to Company

Revision ID: 04f839b466f5
Revises: fdf325c04704
Create Date: 2020-04-26 15:13:40.297530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f839b466f5'
down_revision = 'fdf325c04704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('isin', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'company', ['isin'])
    op.add_column('financial_statement', sa.Column('current_assets', sa.BigInteger(), nullable=True))
    op.add_column('financial_statement', sa.Column('current_liabilities', sa.BigInteger(), nullable=True))
    op.add_column('financial_statement', sa.Column('gross_profit', sa.BigInteger(), nullable=True))
    op.add_column('financial_statement', sa.Column('long_term_liabilities', sa.BigInteger(), nullable=True))
    op.add_column('financial_statement', sa.Column('non_current_assets', sa.BigInteger(), nullable=True))
    op.add_column('financial_statement', sa.Column('operating_income', sa.BigInteger(), nullable=True))
    op.add_column('financial_statement', sa.Column('profit_before_tax', sa.BigInteger(), nullable=True))
    op.drop_column('financial_statement', 'other_revenues')
    op.drop_column('financial_statement', 'profit_before_income_tax')
    op.drop_column('financial_statement', 'operating_profit')
    op.drop_column('financial_statement', 'net_financial_result')
    op.drop_column('financial_statement', 'total_non_current_assets')
    op.drop_column('financial_statement', 'total_current_liabilities')
    op.drop_column('financial_statement', 'total_current_assets')
    op.drop_column('financial_statement', 'total_long_term_liabilities')
    op.drop_column('financial_statement', 'total_operating_expenses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_statement', sa.Column('total_operating_expenses', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('financial_statement', sa.Column('total_long_term_liabilities', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('financial_statement', sa.Column('total_current_assets', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('financial_statement', sa.Column('total_current_liabilities', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('financial_statement', sa.Column('total_non_current_assets', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('financial_statement', sa.Column('net_financial_result', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('financial_statement', sa.Column('operating_profit', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('financial_statement', sa.Column('profit_before_income_tax', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('financial_statement', sa.Column('other_revenues', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('financial_statement', 'profit_before_tax')
    op.drop_column('financial_statement', 'operating_income')
    op.drop_column('financial_statement', 'non_current_assets')
    op.drop_column('financial_statement', 'long_term_liabilities')
    op.drop_column('financial_statement', 'gross_profit')
    op.drop_column('financial_statement', 'current_liabilities')
    op.drop_column('financial_statement', 'current_assets')
    op.drop_constraint(None, 'company', type_='unique')
    op.drop_column('company', 'isin')
    # ### end Alembic commands ###
