"""Added basic models: Company, Financial Statement, Dividend, Value Metric and Daily Ratio

Revision ID: 737eeeeb4441
Revises: d4867f3a4c0a
Create Date: 2020-05-05 13:14:20.487693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737eeeeb4441'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('number_of_shares', sa.BigInteger(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('ipo_date', sa.DateTime(), nullable=True),
    sa.Column('stock_exchange', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.create_table('daily_ratio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('price_to_earnings_ratio_ttm', sa.Float(), nullable=True),
    sa.Column('price_to_book_ratio', sa.Float(), nullable=True),
    sa.Column('market_to_book_ratio', sa.Float(), nullable=True),
    sa.Column('price_to_tangible_book_value', sa.Float(), nullable=True),
    sa.Column('enterprise_value', sa.BigInteger(), nullable=True),
    sa.Column('ev_to_revenue', sa.Float(), nullable=True),
    sa.Column('ev_to_net_income', sa.Float(), nullable=True),
    sa.Column('ev_to_ebit', sa.Float(), nullable=True),
    sa.Column('ev_to_ebitda', sa.Float(), nullable=True),
    sa.Column('ev_to_assets', sa.Float(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_ratio_id'), 'daily_ratio', ['id'], unique=False)
    op.create_table('dividend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('ex_dividend_date', sa.DateTime(), nullable=True),
    sa.Column('pay_date', sa.DateTime(), nullable=True),
    sa.Column('dividend_payout', sa.Float(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dividend_id'), 'dividend', ['id'], unique=False)
    op.create_table('financial_statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('audited', sa.Boolean(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('non_current_assets', sa.BigInteger(), nullable=True),
    sa.Column('cash_and_equivalents', sa.BigInteger(), nullable=True),
    sa.Column('current_assets', sa.BigInteger(), nullable=True),
    sa.Column('total_assets', sa.BigInteger(), nullable=True),
    sa.Column('short_term_debt', sa.BigInteger(), nullable=True),
    sa.Column('current_liabilities', sa.BigInteger(), nullable=True),
    sa.Column('long_term_debt', sa.BigInteger(), nullable=True),
    sa.Column('long_term_liabilities', sa.BigInteger(), nullable=True),
    sa.Column('total_debt', sa.BigInteger(), nullable=True),
    sa.Column('total_liabilities', sa.BigInteger(), nullable=True),
    sa.Column('total_equity', sa.BigInteger(), nullable=True),
    sa.Column('total_equities_and_liabilities', sa.BigInteger(), nullable=True),
    sa.Column('total_revenues', sa.BigInteger(), nullable=True),
    sa.Column('cost_of_revenue', sa.BigInteger(), nullable=True),
    sa.Column('costs_of_goods_sold', sa.BigInteger(), nullable=True),
    sa.Column('gross_profit', sa.BigInteger(), nullable=True),
    sa.Column('ebitda', sa.BigInteger(), nullable=True),
    sa.Column('ebit', sa.BigInteger(), nullable=True),
    sa.Column('operating_income', sa.BigInteger(), nullable=True),
    sa.Column('interest_expense', sa.BigInteger(), nullable=True),
    sa.Column('profit_before_tax', sa.BigInteger(), nullable=True),
    sa.Column('tax_expense', sa.BigInteger(), nullable=True),
    sa.Column('depreciation', sa.BigInteger(), nullable=True),
    sa.Column('amortization', sa.BigInteger(), nullable=True),
    sa.Column('net_income', sa.BigInteger(), nullable=True),
    sa.Column('earnings_per_share', sa.Float(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_financial_statement_id'), 'financial_statement', ['id'], unique=False)
    op.create_table('value_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('book_value', sa.BigInteger(), nullable=True),
    sa.Column('tangible_book_value', sa.BigInteger(), nullable=True),
    sa.Column('tangible_book_value_per_share', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('equity_ratio', sa.Float(), nullable=True),
    sa.Column('debt_ratio', sa.Float(), nullable=True),
    sa.Column('cash_ratio', sa.Float(), nullable=True),
    sa.Column('gross_profit_margin', sa.Float(), nullable=True),
    sa.Column('net_profit_margin', sa.Float(), nullable=True),
    sa.Column('ebit_margin', sa.Float(), nullable=True),
    sa.Column('operating_margin', sa.Float(), nullable=True),
    sa.Column('ebitda_margin', sa.Float(), nullable=True),
    sa.Column('cash_return_on_capital_invested', sa.Float(), nullable=True),
    sa.Column('debt_to_ebitda', sa.Float(), nullable=True),
    sa.Column('return_on_equity', sa.Float(), nullable=True),
    sa.Column('return_on_assets', sa.Float(), nullable=True),
    sa.Column('current_ratio', sa.Float(), nullable=True),
    sa.Column('working_capital', sa.BigInteger(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_value_metrics_id'), 'value_metrics', ['id'], unique=False)
    op.drop_index('ix_item_description', table_name='item')
    op.drop_index('ix_item_id', table_name='item')
    op.drop_index('ix_item_title', table_name='item')
    op.drop_table('item')
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='item_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='item_pkey')
    )
    op.create_index('ix_item_title', 'item', ['title'], unique=False)
    op.create_index('ix_item_id', 'item', ['id'], unique=False)
    op.create_index('ix_item_description', 'item', ['description'], unique=False)
    op.drop_index(op.f('ix_value_metrics_id'), table_name='value_metrics')
    op.drop_table('value_metrics')
    op.drop_index(op.f('ix_financial_statement_id'), table_name='financial_statement')
    op.drop_table('financial_statement')
    op.drop_index(op.f('ix_dividend_id'), table_name='dividend')
    op.drop_table('dividend')
    op.drop_index(op.f('ix_daily_ratio_id'), table_name='daily_ratio')
    op.drop_table('daily_ratio')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
