"""Changed the properties of the ticker column, Company model

Revision ID: fc8b7026fb1b
Revises: 737eeeeb4441
Create Date: 2020-05-11 12:02:28.893963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8b7026fb1b'
down_revision = '737eeeeb4441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_company_ticker'), 'company', ['ticker'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_ticker'), table_name='company')
    # ### end Alembic commands ###
